tue:
  name: Eindhoven University of Technology
  link: https://tue.osiris-student.nl
  code: tue
  active: true
  version: 2
  deeplink: "https://tue.osiris-student.nl/#/onderwijscatalogus/extern/cursus/?cursuscode={code}&collegejaar={year}&taal=en"
  types:
    - - BC
      - Bachelor College
    - - GS
      - Graduate School
  faculties:
    - - BMT
      - Biomedische Technologie
    - - B
      - Bouwkunde
    - - ESOE
      - Eindhoven School of Education
    - - EE
      - Electrical Engineering
    - - ID
      - Industrial Design
    - - IE&IS
      - Industrial Engineering & Innovation Sciences
    - - ST
      - Scheikundige Technologie
    - - TN
      - Technische Natuurkunde
    - - W
      - Werktuigbouwkunde
    - - W&I
      - Wiskunde en Informatica
    - - HON.ACAD.
      - Honors Academy
    - - JADS
      - Jheronimus Academy of Data Science
uu:
  name: Universiteit Utrecht
  link: https://osiris.uu.nl/osiris_student_uuprd/
  code: uu
  active: true
  types:
    - - CURSUS
      - Courses
ut:
  name: University of Twente
  link: https://osiris.utwente.nl/student/
  code: ut
  active: true
  types:
    - - CURSUS
      - Courses
    - - HONOURS
      - Honours
    - - MODULE
      - Module courses
    - - MODULECURSUS
      - Independent Module Courses
ru:
  name: Radboud Universiteit
  link: https://sis.ru.nl/osiris-student/
  code: ru
  active: true
  types:
    - - CURSUS
      - Courses
    - - HONOURS
      - Honours
    - - PRACTICUM
      - Practical Lab

tud:
  name: Technische Universiteit Delft
  link: https://osistud.tudelft.nl/osiris_student/
  code: tud
  active: false
  types:
    - - CURSUS
      - Courses